### PR TITLE
Auto-fill album for artist and track (closes #88)

### LINKED ISSUE #88: Auto-fill album title based on artist+song
**Description**
>Given you already look up the catalogue for scrobbling full albums, how about a button to "predict" the album title once I've filled in the artist and title? The biggest slow down when I'm manually scrobbling is finding out what album the song is from, whereas your site could theoretically grab that info for me by showing me what Last.fm has as that song's album.
>
> So for example, if I filled in:
>
>Artist: ABBA
>Title: Knowing Me, Knowing You
>
>If I then clicked an icon next to album, it would fill in the text field with Arrival. If I'm not happy with that result I could change or remove it, but it'd save a lot of time looking around for the title and it's not something other scrobblers do yet :smiley: 

**Additional context**
Suggested on Discord by KatyB

### PR DESCRIPTION
**Pull request by mishmish-dev**
The feature uses last.fm API trackGetInfo to retrieve an album name based on track + artist.

To complete this, I'd ask for help with a couple of things:
1) Translation, I added two new tooltips;
2) Creating some animation telling user of success/failure of the operation.

Things to consider: rate-limit last.fm API calls? Delegate to backend?

### CODE REVIEW

**Comment by mishmish-dev** [comment]
@elamperti
Regarding item 2, I could try to re-use the catch-paste alert, but how to test alerts locally?

**Comment by elamperti** [comment]
The alerts use a context, so you can dispatch messages easily. I think that, for this feature, perhaps it would be more appropriate to show a spinner within the input (when loading) and create a "shake" animation if there's a failure (or some other indicator around this field).

**Comment by mishmish-dev** [comment]
Hmm, when I run OpenScrobbler locally, the catch-paste thing doesn't work.

Anyway, I would be glad if you add this animation. I am really not a frontend guy.

**Comment by elamperti** [comment]
Sure! I'll look into it. 

To catch pasted text, you should have the corresponding option enabled (from the settings modal)

**Comment by mishmish-dev** [comment]
Hi @elamperti 
I implemented shakey animation for album auto-fill failure, as well as highlighting the input field with cyan/red on success/fail

**Comment by elamperti** [comment]
Awesome! I'm a bit backed up with a few other upcoming changes but I'll review and merge as soon as possible. Thanks for your work and patience! 😁

**Comment by mishmish-dev** [comment]
Resolved conflict with the main branch in previous commit

**Comment by elamperti** [comment]
Thank you! I'm finishing with a few adjustments on #237 and I'll get to this one \o/

**Review by elamperti — APPROVED** [review]
Fantastic! Great job adding the animation as well 😃

**Pull request merged**
