### PR TITLE
front-end improvements

### LINKED ISSUE #23: The spinning disc icon looks drunk
When a track is scrobbling, the web app displays an animated disc to show activity. However, the disc is not center-aligned, which means that the spinning animation makes it look like it’s drunk :joy_cat:

### LINKED ISSUE #30: Scrobble again button misplaced for long strings
selection_034

### PR DESCRIPTION
**Pull request by maksiuP**
- switched to bootstrap v4
- added popper.js, which is required by bootstrap
- switched to jquery 3.3.1
- bootstrap, popper and jquery js files are loaded from external cdns
- switched from glyphicons to fontello. fontello loads only necessary icons, which reduces page size
- external links now open in new tab
- collapsing menu fixed (it blinked on mobile devices)
- switched to newer versions of datepicker and clockpicker
- modified datepicker and clockpicker stylesheets to match color theme
- fixed #30 
- fixed #23

### CODE REVIEW

**Comment by elamperti** [comment]
@maksiuP hey, thanks so much for all this work! I'm about to push a refactored version of the project (using React, Bootstrap 4, FontAwesome and new components), so I'm afraid I can't merge this PR (I'm sorry about that! It looks like you did a great work here). I'll let you know as soon as it's up, I think you will like it!

Thanks again! :)

**Comment by maksiuP** [comment]
fontello generates icon font files, which include only necessary icons (also from fontawesome), so we don't load unnecessary icons. few icons i've used are from fontawesome.
i'm also working on using vue, which is js framework, like react, but, imo, better, faster and easier to use.
could you push your refactored version on other branch, so i can have a look at it?

**Comment by elamperti** [comment]
Using FontAwesome 5 icons will be embedded in SVG; it saves a lot of bandwidth and I think there shouldn't be need for fontello (as icons are imported individually as well).

Regarding Vue: I really like it and I've been working on a Vue project for the past year. I agree it's easier to use! (and faster, though at this scale the difference won't be noticeable). I decided to go with React for two reasons: a personal one (I wanted to learn React and this was the perfect project for that) and because it's more approachable for -most- developers. Vue has a lot of interest, but -from my work experience- not as many available developers (though I acknowledge the number is increasing). In the end both are great options! I'll stick with React because I've been working on this new version for weeks already and I think it's a good fit for this project.

I'll upload the changes in a week or so, as I'm ironing out some details on new features and CI. I'll let you know as soon as it's available!

Please keep this PR open for now, I may be able to rebase my branch on top of it so we can keep your contribution in the repo's history, as I'd like you to figure among the contributors.

**Comment by elamperti** [comment]
Just a quick update: I'm still working on the refactor -big things coming!-, though I'm also busy with work, so it's taking me a bit longer than initially expected. It'll be worth the wait :)

**Pull request closed without merging**
